# Generated by Django 6.0.6 on 2026-07-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_dailysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sparkline',
            field=models.JSONField(default=list),
        ),
    ]
