# Generated by Django 6.0.6 on 2026-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_stock_sparkline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(default=10000000),
        ),
    ]
